language: node_js

node_js:
  - "node"
  - "8"
  - "7"

after_script:
  - npm i -g coveralls
  - npm run test:coverage
  - npx nyc report --reporter=text-lcov | coveralls

deploy:
  provider: npm
  email: fabian.schneider@maxdome.de
  api_key: $NPM_TOKEN
  on:
    tags: true
